lidar0:
    topic: /livox/lidar
    is_livox: true
    Extrinsics:
        time_offset: 0.000
        # LiDAR in IMU /livox/imu    
        Trans: [0.04165, 0.02326, -0.0284]
        Rot: [1.00000, 0.00000, 0.00000,
            0.00000, 1.00000, 0.00000,
            0.00000, 0.00000, 1.00000]
num_lidars: 1

################### FeatureExtraction ###################
Livox:
    n_scan: 6
    blind: 0.1        #0.5 Livox Avia cannot precisely detect objects which are less than 1m away.
    inf_bound: 4     #10  Livox Avia can precisely detect objects 450m away.
    group_size: 8
    disA: 0.01
    disB: 0.1
    limit_maxmid: 6.25
    limit_midmin: 6.25
    limit_maxmin: 3.24
    p2l_ratio: 225
    jump_up_limit: 170.0
    jump_down_limit: 8.0
    edgea: 2
    edgeb: 0.1
    smallp_intersect: 172.5
    smallp_ratio: 1.2
    point_filter_num: 1

    edge_threshold: 1.0
    surf_threshold: 0.1
    odometry_surface_leaf_size: 0.2           # default: 0.4 - outdoor, 0.2 - indoor
    min_distance: 1.0
    max_distance: 100.0

################### Odometry ###################
use_corner_feature: true

current_scan_param:
    corner_leaf_size: 0.1                 # default: 0.2 - outdoor, 0.2 - indoor   !0.2
    surface_leaf_size: 0.1                # default: 0.4 - outdoor, 0.4 - indoor   !0.4

    edge_min_valid_num: 10
    surf_min_valid_num: 100

    correspondence_downsample: 1          # !2

keyframe_strategy:
    angle_degree: 10 #30
    dist_meter: 1.0
    time_second: 3 #10                    # !5
    
map_param:    
    keyframe_search_radius: 35.0          # default: 30 - outdoor, 10 - indoor     !30.0
    keyframe_search_time: 10.0            # 最近几秒的数据构建局部地图                  !8
    keyframe_density: 2                   # default: 2 - outdoor,  0.5 - indoor


################### LoopClosure ###################
loop_closure_enable_flag: false
loop_closure_frequency: 0.04

use_full_cloud: true  
icp_manual_check: true

scan_search_radius: 10.0
scan_search_num: 30
scan_time_diff: 35.0
scan_index_diff: 50

scan_fitness_score: 5.0
loop_closure_downsample_leaf_size: 0.4

loop_closure_weights:
    pose_graph_edge_pos_weight: 20.0
    pose_graph_edge_rot_weight: 40.0
    velocity_weight: 2.0
    gyro_weight: 2.0
